version: '3.7'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile-AuthService
    environment:
      Logging:LogLevel_Default: Warning
    ports:
      - target: 80

    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

      labels:
        # Traefik 2.0
        traefik.enable: "true"
        traefik.docker.network: internal

        traefik.http.routers.auth-http.rule: PathPrefix(`/authservice`)
        traefik.http.routers.auth-http.entrypoints: "http"
        #traefik.http.routers.auth-http.middlewares: "auth-redirect@docker"

        traefik.http.routers.auth-http.middlewares: "auth-stripprefix@docker"

        #traefik.http.routers.auth-https.rule: PathPrefix(`/authservice`)
        #traefik.http.routers.auth-https.entrypoints: "https"
        #traefik.http.routers.auth-https.middlewares: "auth-stripprefix@docker"
        #traefik.http.routers.auth-https.tls: "true"

        #traefik.http.middlewares.auth-redirect.redirectscheme.scheme: "https"
        traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes: /authservice
        traefik.http.services.auth.loadbalancer.server.port: 80

networks:
  internal:
    driver: overlay
    external: true
