version: '3.7'

services:
  account:
    build:
      context: .
      dockerfile: Dockerfile-AccountService
    environment:
      Logging:LogLevel_Default: Warning
    ports:
      - target: 80

    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

      labels:
        # Traefik 2.0
        traefik.enable: "true"
        traefik.docker.network: internal

        traefik.http.routers.account-http.rule: PathPrefix(`/accountservice`)
        traefik.http.routers.account-http.entrypoints: "http"
        #traefik.http.routers.account-http.middlewares: "account-redirect@docker"

        traefik.http.routers.account-https.middlewares: "account-stripprefix@docker"

        #traefik.http.routers.account-https.rule: PathPrefix(`/accountservice`)
        #traefik.http.routers.account-https.entrypoints: "https"
        #traefik.http.routers.account-https.middlewares: "account-stripprefix@docker"
        #traefik.http.routers.account-https.tls: "true"

        #traefik.http.middlewares.account-redirect.redirectscheme.scheme: "https"
        traefik.http.middlewares.account-stripprefix.stripprefix.prefixes: /accountservice
        traefik.http.services.account.loadbalancer.server.port: 80

networks:
  internal:
    driver: overlay
    external: true
